### ISSUE TITLE
My last pull request changed your lib too much

### ISSUE THREAD

**Issue by cswank** [The5heepDev/tidal#3]
Hello, I think the last PR that you accepted from me changed your lib too much.  After I made that first commit I decided my app needs better error handling.  I pushed another commit to my fork that adds the error handling and forgot that I had an open PR with your repo.  As a result your example app is now broken.  

Sorry about that.  If you want I can make another PR that uses the error handling in your tidal wave app, or I can make another PR that reverts the second 'wip' commit.

**Comment by ozwaldorf** [comment]
If you want to fix tidal wave and submit a PR, it would be much appreciated!

**Comment by cswank** [comment]
Cool, I should have something the weekend.
